### ISSUE TITLE
Not able to get this working inside docker

### ISSUE THREAD

**Issue by acetinick** [spatie/ruby-ray#14]
I see documentation on PHP for docker,  but we need to override host and port settings to make this work inside docker.

We should add some initialisation options for setting host and port to communicate to the desktop app

eg.
/config/initializer/ray.rb

Ray.host = 'host.docker.internal'
Ray.port = 23516

**Comment by acetinick** [comment]
Looks like this will be solved with #12 ,  @freekmurze  if we could have this merged.  Currently can't use our Ray license within my team.

**Comment by freekmurze** [comment]
Hi, the implementation of #12 seems incomplete. Config should be read from a file. I'm currently short on time to add this myself, but I'd accept a PR.

>  Currently can't use our Ray license within my team.

What is the exact problem you are facing?

**Comment by acetinick** [comment]
As above, doesn’t work inside docker without being able to override host and port

**Comment by acetinick** [comment]
As per above, can’t use ray inside docker without being able to set host and port via initialiser

**Comment by acetinick** [comment]
Any update on this @freekmurze ? We paid licenses for our developers but still can't use (

**Comment by freekmurze** [comment]
Hi, I'm sorry, but I am short on time. 

If you need this fast, I'd appreciate a PR that adds reading a config file (much like the php ray package).

To get started now with ray, you could use the version of the gem of the PR.

**Comment by acetinick** [comment]
trying to use PR but doesn't work for me.

config file goes against Rails standards, and initializer should be used like all other gems.

Sorry but I short on time too to do PR for your paid product.
