### ISSUE TITLE
Read a settings file

### ISSUE THREAD

**Issue by freekmurze** [spatie/ruby-ray#3]
Right the now the settings are hard coded.

https://github.com/spatie/ruby-ray/blob/5502024c2c99e13f378a4bd35315f8b279f28236/lib/ray.rb#L146

Before using the default, we should try to see if there is a config file that can be read in the project directory or any of the parent directories (much like [what is being done](https://spatie.be/docs/ray/v1/configuration/general) in the other Ray packages)

**Comment by jespr** [comment]
Let's use initializers for this - I can take a stab at it!
